# Generated by Django 4.0.3 on 2022-07-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=50, verbose_name='Назва категорії')),
                ('Category_desc', models.TextField(max_length=50, verbose_name='Короткий опис товарів у категорії')),
            ],
        ),
    ]
