# Generated by Django 4.0.3 on 2022-07-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0002_alter_categories_options_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_final_price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=15, verbose_name='Кінцева ціна'),
        ),
    ]
