# Generated by Django 4.0.3 on 2022-07-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0006_alter_products_product_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_final_price',
        ),
        migrations.AddField(
            model_name='products',
            name='product_png',
            field=models.ImageField(default=0, upload_to='img/%Y/%m/%d'),
        ),
    ]
