# Generated by Django 4.0.3 on 2022-07-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0007_remove_products_product_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date_add',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_png',
            field=models.ImageField(default=0, upload_to='main_shop\\static\\main_shop\\img\\%Y\\%m\\%d'),
        ),
    ]
