# Generated by Django 4.0.3 on 2022-07-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0009_remove_products_date_add_products_date_of_get_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='unit_of_measure',
            field=models.CharField(default='кг', max_length=150, verbose_name='Одиниці вимірювання'),
        ),
    ]
