# Generated by Django 4.0.6 on 2022-07-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0010_alter_products_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_png',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='media'),
        ),
    ]
