# Generated by Django 4.0.6 on 2022-07-31 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_shop', '0012_alter_products_product_png'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_products', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='кількість товару')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_shop.products', verbose_name='ID Товару')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
