# Generated by Django 4.0.3 on 2022-07-31 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0014_order_in_wrork'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_in_wrork',
            name='ord_name',
            field=models.CharField(default=0, max_length=2000, verbose_name="Ім'я отримувача"),
        ),
        migrations.AddField(
            model_name='order_in_wrork',
            name='ord_surname',
            field=models.CharField(default=0, max_length=2000, verbose_name="Ім'я отримувача"),
        ),
        migrations.AddField(
            model_name='order_in_wrork',
            name='phone_number',
            field=models.CharField(blank=True, default=0, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='order_in_wrork',
            name='additional_info',
            field=models.CharField(default=0, max_length=2000, verbose_name='Додаткова інформація'),
        ),
        migrations.AlterField(
            model_name='order_in_wrork',
            name='adress',
            field=models.CharField(default=0, max_length=2000, verbose_name='Адреса користувача'),
        ),
        migrations.AlterField(
            model_name='order_in_wrork',
            name='order_info',
            field=models.CharField(default=0, max_length=2000000, verbose_name='Дані про замовлення'),
        ),
    ]
