# Generated by Django 4.0.3 on 2022-07-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0015_order_in_wrork_ord_name_order_in_wrork_ord_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_in_wrork',
            name='user_id',
            field=models.CharField(default=0, max_length=2000, verbose_name='Username'),
        ),
    ]
