# Generated by Django 4.0.3 on 2022-07-31 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0016_alter_order_in_wrork_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=2000, verbose_name='Username')),
                ('product_count', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Кількість товару')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_shop.products')),
            ],
        ),
    ]
