# Generated by Django 4.0.3 on 2022-07-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0017_preorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.CharField(default=0, max_length=200, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='user_id',
            field=models.CharField(default=0, max_length=200, verbose_name='Username'),
        ),
    ]
