# Generated by Django 4.0.3 on 2022-07-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0019_alter_orders_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_name',
            field=models.CharField(default=0, max_length=200, verbose_name='Назва продукту'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_png',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='media\\img\\%Y\\%m\\%d'),
        ),
    ]
