# Generated by Django 4.0.3 on 2022-08-01 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0020_orders_product_name_orders_product_png'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ціна замовлення'),
        ),
    ]
