# Generated by Django 4.0.3 on 2022-08-01 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0021_orders_product_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product_final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ціна замовлення'),
        ),
    ]
